### ISSUE TITLE
arm mac build

### ISSUE THREAD

**Issue by 0xr0bert** [conda-forge/r-traminer-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Could we get an arm mac build of this?

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by mfansler** [comment]
Thanks for raising this! I put in a migration request for you. In the future, you are welcome to trigger migration for any package directly by submitting a PR to the **conda-forge-pinning-feedstock** (see [documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)). Conda Forge only builds for **osx-arm64** by request, so if anything else you need is missing please continue requesting.

**Comment by mfansler** [comment]
This should be up on Anaconda Cloud in 1-2 hours. https://github.com/conda-forge/r-traminer-feedstock/pull/12
